"""Assemble a ready-to-push bundle of the public, read-only dashboard.

    python -m cyberarena.showcase                               # 1. export the published runs into showcase/
    python -m cyberarena.deploy                                 # 2. assemble build/streamlit-cloud
    # 3. commit that folder to the `showcase` branch and deploy it on Streamlit Community Cloud (README > Hosting)

Targets:
  streamlit  (default) a plain repo for Streamlit Community Cloud (free). Main file: src/cyberarena/dashboard/app.py
  hf-docker  a Hugging Face Docker Space (needs a paid HF plan)

A bundle contains only the dashboard code, the showcase data, the Streamlit theme and a slim requirements file. No
training code, model weights or full logs are deployed. A PUBLIC_SHOWCASE marker at the bundle root switches the app
to public read-only mode on any host, with no environment settings needed.
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

from cyberarena import config

TARGETS = ("streamlit", "hf-docker")
SPACE_PORT = 7860
PACKAGE_FILES = ("__init__.py", "config.py", "showcase.py")
MAIN_FILE = "src/cyberarena/dashboard/app.py"

DOCKERFILE = f"""FROM python:3.12-slim

# Hugging Face Spaces run containers as uid 1000.
RUN useradd -m -u 1000 user
USER user
ENV HOME=/home/user \\
    PATH=/home/user/.local/bin:$PATH \\
    PYTHONPATH=/home/user/app/src \\
    CYBERARENA_PUBLIC=1 \\
    CYBERARENA_RUNS_DIR=/home/user/app/showcase \\
    STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
WORKDIR /home/user/app

COPY --chown=user requirements.txt .
RUN pip install --no-cache-dir --user -r requirements.txt
COPY --chown=user . .

EXPOSE {SPACE_PORT}
CMD ["streamlit", "run", "{MAIN_FILE}", "--server.port={SPACE_PORT}", \\
     "--server.address=0.0.0.0", "--server.headless=true"]
"""

ABOUT = """Read-only dashboard for a simulated red-team vs blue-team reinforcement-learning project. Every run shown here
was trained offline by the author; this deployment only displays the results. Source, methods and limitations:
https://github.com/DazedSoup/ai-solutions
"""

SPACE_README = f"""---
title: cyberarena
emoji: 🛡️
colorFrom: indigo
colorTo: red
sdk: docker
app_port: {SPACE_PORT}
pinned: false
license: mit
short_description: Red vs blue RL agents with adaptive TensorFlow detectors
---

# cyberarena: public showcase

{ABOUT}"""

STREAMLIT_README = f"""# cyberarena: public showcase

{ABOUT}
This repository is generated by `python -m cyberarena.deploy`; don't edit it by hand.

Deploy on [Streamlit Community Cloud](https://share.streamlit.io): **Create app**, then choose this repository, branch
`showcase`, and main file path `{MAIN_FILE}`. Under *Advanced settings*, pick **Python 3.12**.
"""


def _ignore(_dir: str, names: list[str]) -> set[str]:
    return {n for n in names if n == "__pycache__" or n.endswith((".pyc", ".pyo"))}


def assemble(out: Path, showcase: Path, root: Path | None = None, target: str = "streamlit") -> dict:
    if target not in TARGETS:
        raise ValueError(f"unknown target {target!r} (choose from {', '.join(TARGETS)})")
    root = root or config.ROOT
    if not (showcase / "MANIFEST.json").exists():
        raise FileNotFoundError(f"{showcase} has no MANIFEST.json; run `python -m cyberarena.showcase` first")
    if out.exists():  # rebuild everything except the bundle's own git checkout, so later deploys are plain pushes
        for child in out.iterdir():
            if child.name == ".git":
                continue
            shutil.rmtree(child) if child.is_dir() else child.unlink()
    pkg_src, pkg_dst = root / "src" / "cyberarena", out / "src" / "cyberarena"
    pkg_dst.mkdir(parents=True)
    for name in PACKAGE_FILES:
        shutil.copy2(pkg_src / name, pkg_dst / name)
    shutil.copytree(pkg_src / "dashboard", pkg_dst / "dashboard", ignore=_ignore)
    shutil.copytree(showcase, out / "showcase")
    if (root / ".streamlit").is_dir():
        shutil.copytree(root / ".streamlit", out / ".streamlit")
    shutil.copy2(root / "requirements-dashboard.txt", out / "requirements.txt")
    shutil.copy2(root / "LICENSE", out / "LICENSE")
    (out / "PUBLIC_SHOWCASE").write_text("This bundle runs the dashboard in public read-only mode.\n",
                                         encoding="utf-8", newline="\n")  # fmt: skip
    (out / ".gitignore").write_text("__pycache__/\n*.pyc\n", encoding="utf-8", newline="\n")
    if target == "hf-docker":
        (out / "Dockerfile").write_text(DOCKERFILE, encoding="utf-8", newline="\n")
        (out / "README.md").write_text(SPACE_README, encoding="utf-8", newline="\n")
        # Hugging Face rejects plain-git files over 10 MB; store the showcase data with git-lfs.
        (out / ".gitattributes").write_text("showcase/** filter=lfs diff=lfs merge=lfs -text\n", encoding="utf-8",
                                            newline="\n")  # fmt: skip
    else:
        (out / "README.md").write_text(STREAMLIT_README, encoding="utf-8", newline="\n")
    size = sum(p.stat().st_size for p in out.rglob("*") if p.is_file() and ".git" not in p.relative_to(out).parts)
    return {"out": str(out), "bytes": size, "target": target,
            "manifest": json.loads((showcase / "MANIFEST.json").read_text("utf-8"))}  # fmt: skip


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="python -m cyberarena.deploy", description=__doc__.split("\n\n")[0])
    ap.add_argument("--target", choices=TARGETS, default="streamlit")
    ap.add_argument("--out", type=Path, default=None, help="default: build/streamlit-cloud or build/hf-space")
    ap.add_argument("--showcase", type=Path, default=config.ROOT / "showcase")
    args = ap.parse_args(argv)
    out = args.out or config.ROOT / "build" / ("streamlit-cloud" if args.target == "streamlit" else "hf-space")
    try:
        info = assemble(out, args.showcase, target=args.target)
    except FileNotFoundError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2
    m = info["manifest"]
    print(f"assembled {info['out']} for {info['target']} ({info['bytes'] / 1e6:.1f} MB): "
          f"{len(m.get('runs', []))} runs, {len(m.get('experiments', []))} experiments")  # fmt: skip
    print("next: commit and push this folder on the showcase branch (README > Hosting a public showcase)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
